# Generated by Django 2.2.2 on 2019-06-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='converter',
            old_name='user',
            new_name='user_info',
        ),
    ]
